api_platform:
    metadata_backward_compatibility_layer: false
    title: 'API produit multimag'
    description: 'Gestion des produits'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header
